repos:

  - repo: git@github.com:PyCQA/isort.git
    rev: 5.10.1
    hooks:
      - id: isort
        name: sort all imports (python)

  - repo: git@github.com:pre-commit/mirrors-yapf.git
    rev: v0.32.0
    hooks:
    - id: yapf
      name: yapf formatter
      args: ['--style=.style.yapf', '--parallel', '--in-place']

  - repo: git@github.com:pre-commit/mirrors-clang-format.git
    rev: v13.0.1
    hooks:
    - id: clang-format
      name: clang formatter

  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
